name: candidate_freeze

on:
  workflow_dispatch:
  schedule:
    # 02-15 through 03-14:
    - cron: '0 * 15-31 2 *' # minute 0 every hour in February day 15 and after
    - cron: '0 * 1-14 3 *'  # minute 0 every hour in March day 14 and before
    # 05-15 through 06-14:
    - cron: '0 * 15-31 5 *' # minute 0 every hour in May day 15 and after
    - cron: '0 * 1-14 6 *'  # minute 0 every hour in June day 14 and before
    # 08-15 through 09-14:
    - cron: '0 * 15-31 8 *' # minute 0 every hour in August day 15 and after
    - cron: '0 * 1-14 9 *'  # minute 0 every hour in September day 14 and before
    # 11-15 through 12-14:
    - cron: '0 * 15-31 11 *' # minute 0 every hour in November day 15 and after
    - cron: '0 * 1-14 12 *'  # minute 0 every hour in December day 14 and before

jobs:
  candidate_freeze:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libglpk-dev

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        run: |
          install.packages("pak")
          pak::pkg_install("r-multiverse/multiverse.internals@*release")
        shell: Rscript {0}

      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Record versions.
        run: |
          multiverse.internals::record_versions(
            versions = "versions.json",
            repo = "https://staging.r-multiverse.org"
          )
        shell: Rscript {0}

      - name: Record status.
        run: |
          multiverse.internals::record_status(
            repo = "https://staging.r-multiverse.org",
            versions = "versions.json",
            output = "status.json"
          )
        shell: Rscript {0}

      - name: Record non-standard licenses.
        run: |
          multiverse.internals::record_nonstandard_licenses(
            repo = "https://staging.r-multiverse.org",
            path = "nonstandard_licenses.json"
          )
        shell: Rscript {0}

      - name: Stage packages.
        shell: Rscript {0}
        run: multiverse.internals::stage_candidates(path_staging = getwd())

      - name: Commit and push changes.
        run: |
          git add *.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -m "Candidate freeze"
            git push -u origin main
          fi
