name: dependency_freeze

on:
  workflow_dispatch:
  schedule:
    # 01-15 through 02-14:
    - cron: '0 0 15-31 1 *' # every hour every day in January day 15 and after
    - cron: '0 0 1-14 2 *'  # every hour every day in February day 14 and before
    # 04-15 through 05-14:
    - cron: '0 0 15-31 4 *' # every hour every day in April day 15 and after
    - cron: '0 0 1-14 5 *'  # every hour every day in May day 14 and before
    # 07-15 through 08-14:
    - cron: '0 0 15-31 7 *' # every hour every day in July day 15 and after
    - cron: '0 0 1-14 8 *'  # every hour every day in August day 14 and before
    # 10-15 through 11-14:
    - cron: '0 0 15-31 10 *' # every hour every day in October day 15 and after
    - cron: '0 0 1-14 11 *' # every hour every day in November day 14 and before

jobs:
  dependency_freeze:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev libglpk-dev

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        shell: Rscript {0}
        run: |
          install.packages("pak")
          pak::pkg_install("r-multiverse/multiverse.internals@*release")

      - name: Check out the Staging universe.
        uses: actions/checkout@v4

      - name: Check out the Community universe.
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/community'
          path: 'community'

      - name: Freeze dependencies.
        shell: Rscript {0}
        run: |
          multiverse.internals::freeze_dependencies(
            path_staging = getwd(),
            path_community = "community"
          )

      - name: Clean up.
        run: rm -rf community

      - name: Commit and push changes.
        run: |
          git add *.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Dependency freeze"
            git push -u origin main
          fi
