name: finalize

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 3 *'  # 12:00 AM on March 15
    - cron: '0 0 15 6 *'  # 12:00 AM on June 15
    - cron: '0 0 15 9 *'  # 12:00 AM on September 15
    - cron: '0 0 15 12 *' # 12:00 AM on December 15

jobs:
  finalize:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Finalize staging.
        run: |
          cp snapshot.json packages.json
          rm -f config.json

      - name: Commit and push changes.
        run: |
          git add *.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Reset staging"
            git push -u origin main
          fi
