# MIT License
# 
# Copyright (c) 2024 Jeroen Ooms
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: production

on:
  workflow_dispatch:
  schedule:
    # 02-15 through 03-15:
    - cron: '0 0 15-31 2 *' # 12:00 AM on February 15 and after
    - cron: '0 0 1-15 3 *'  # 12:00 AM on March 15 and before
    # 05-15 through 06-15:
    - cron: '0 0 15-31 5 *' # 12:00 AM on May 15 and after
    - cron: '0 0 1-15 6 *'  # 12:00 AM on June 15 and before
    # 08-15 through 09-15:
    - cron: '0 0 15-31 8 *' # 12:00 AM on August 15 and after
    - cron: '0 0 1-15 9 *'  # 12:00 AM on September 15 and before
    # 11-15 through 12-15:
    - cron: '0 0 15-31 11 *' # 12:00 AM on November 15 and after
    - cron: '0 0 1-15 12 *'  # 12:00 AM on December 15 and before

jobs:
  production:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Update existing system libraries.
        run: sudo apt-get update

      - name: Install R package system dependencies.
        run: sudo apt-get install libcurl4-openssl-dev libglpk-dev
    
      - name: Install Rclone.
        run: sudo -v; curl https://rclone.org/install.sh | sudo bash

      - name: Install R.
        uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://community.r-multiverse.org
          use-public-rspm: true

      - name: Install helper R package.
        run: install.packages("multiverse.internals")
        shell: Rscript {0}

      - name: Store snapshot date as environment variable.
        run: echo "DATE=$(Rscript -e 'cat(multiverse.internals::date_snapshot())')" >> $GITHUB_ENV

      - name: Print target snapshot date.
        run: echo $DATE

      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Configure rclone.
        run: |
          rclone config create production s3 \
            provider=Cloudflare \
            access_key_id=${{ secrets.CLOUDFLARE_ACCESS_KEY_ID }} \
            secret_access_key=${{ secrets.CLOUDFLARE_SECRET_ACCESS_KEY }} \
            endpoint=https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com \
            acl=private \
            no_check_bucket=true

      - name: Download snapshot.
        run: cat snapshot.url | xargs curl -sS | tar xvzf -

      - name: Upload sources.
        run: |
          rclone sync src/contrib production:${{ secrets.CLOUDFLARE_BUCKET }}/$DATE/src/contrib \
            --checkers 8 --transfers 8 \
            --progress \
            --exclude PACKAGES --exclude PACKAGES
      
      - name: Upload metadata.
        run: |
          rclone copy src/contrib/PACKAGES production:${{ secrets.CLOUDFLARE_BUCKET }}/$DATE/src/contrib --progress
          rclone copy src/contrib/PACKAGES.gz production:${{ secrets.CLOUDFLARE_BUCKET }}/$DATE/src/contrib --progress
          rclone copy meta.json production:${{ secrets.CLOUDFLARE_BUCKET }}/$DATE --progress

      - name: Upload binaries.
        run: |
          rclone sync bin production:${{ secrets.CLOUDFLARE_BUCKET }}/$DATE/bin \
            --checkers 8 --transfers 8 \
            --progress

      - name: Update snapshot list.
        run: |
          rclone copy --include="*/meta.json" --max-depth 2 production:${{ secrets.CLOUDFLARE_BUCKET }}/ ./meta/
          jq -cs 'add' ./meta/**/meta.json > snapshots.json
          rclone copy snapshots.json production:${{ secrets.CLOUDFLARE_BUCKET }}
