name: reset

on:
  workflow_dispatch:
  schedule:
    # 01-15 through 02-14:
    - cron: '0 0 15-31 1 *' # on the first minute of every day in January day 15 and after
    - cron: '0 0 1-14 2 *'  # on the first minute of every day in February day 14 and before
    # 04-15 through 05-14:
    - cron: '0 0 15-31 4 *' # on the first minute of every day in April day 15 and after
    - cron: '0 0 1-14 5 *'  # on the first minute of every day in May day 14 and before
    # 07-15 through 08-14:
    - cron: '0 0 15-31 7 *' # on the first minute of every day in July day 15 and after
    - cron: '0 0 1-14 8 *'  # on the first minute of every day in August day 14 and before
    # 10-15 through 11-14:
    - cron: '0 0 15-31 10 *' # on the first minute of every day in October day 15 and after
    - cron: '0 0 1-14 11 *' # on the first minute of every day in November day 14 and before

jobs:
  reset_staging:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Clone multiverse.internals.
        uses: actions/checkout@v4
        with:
          repository: '${{ github.repository_owner }}/multiverse.internals'
          path: 'multiverse.internals'

      - name: Reset staging.
        run: |
          cd multiverse.internals
          HASH=$(git rev-parse HEAD)
          cd ..
          rm -rf multiverse.internals
          echo "[{\"package\":\"multiverse.internals\",\"url\":\"https://github.com/r-multiverse/multiverse.internals\",\"branch\":\"$HASH\"}]" > packages.json

      - name: Commit and push changes.
        run: |
          git add *.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Reset staging"
            git push -u origin main
          fi
