name: reset

on:
  workflow_dispatch:
  schedule:
    # 12-15 through 01-14:
    - cron: '0 * 15-31 12 *' # minute 0 every hour in December day 15 and after
    - cron: '0 * 1-14 1 *'  # minute 0 every hour in January day 14 and before
    # 03-15 through 04-14:
    - cron: '0 * 15-31 3 *' # minute 0 every hour in March day 15 and after
    - cron: '0 * 1-14 4 *'  # minute 0 every hour in April day 14 and before
    # 06-15 through 07-14:
    - cron: '0 * 15-31 6 *' # minute 0 every hour in June day 15 and after
    - cron: '0 * 1-14 7 *'  # minute 0 every hour in July day 14 and before
    # 09-15 through 10-14:
    - cron: '0 * 15-31 9 *' # minute 0 every hour in September day 15 and after
    - cron: '0 * 1-14 10 *'  # minute 0 every hour in October day 14 and before

jobs:
  reset_staging:
    runs-on: macOS-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Reset staging.
        run: rm packages.json

      - name: Commit and push changes.
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Reset staging"
            git push -u origin main
          fi
