name: reset

on:
  workflow_dispatch:
  schedule:
    # 12-15 through 01-14:
    - cron: '0 0 15-31 12 *' # on the first minute of every day in December day 15 and after
    - cron: '0 0 1-14 1 *'  # on the first minute of every day in January day 14 and before
    # 03-15 through 04-14:
    - cron: '0 0 15-31 3 *' # on the first minute of every day in March day 15 and after
    - cron: '0 0 1-14 4 *'  # on the first minute of every day in April day 14 and before
    # 06-15 through 07-14:
    - cron: '0 0 15-31 6 *' # on the first minute of every day in June day 15 and after
    - cron: '0 0 1-14 7 *'  # on the first minute of every day in July day 14 and before
    # 09-15 through 10-14:
    - cron: '0 0 15-31 9 *' # on the first minute of every day in September day 15 and after
    - cron: '0 0 1-14 10 *' # on the first minute of every day in October day 14 and before

jobs:
  reset_staging:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Check out the staging universe.
        uses: actions/checkout@v4

      - name: Reset staging.
        run: rm -f packages.json

      - name: Commit and push changes.
        run: |
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git config --global user.name github-actions
            git config --global user.email actions@github.com
            git commit -am "Reset staging"
            git push -u origin main
          fi
